name: Build and deploy Pandoc application

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build-pandoc-wasm:
    name: Build pandoc-wasm
    runs-on: self-hosted
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup git submodules
        run: make submodules
      - name: Pull Docker container
        run: docker pull ghcr.io/georgestagg/pandoc-wasm:main
      - name: Tag Docker container
        run: docker image tag ghcr.io/georgestagg/pandoc-wasm:main pandoc-wasm
      - name: Build pandoc-wasm
        run: make
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
      - name: Publish to npm
        if: "!contains(github.ref_name, 'main')"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public
